#baseURL= ""
#title = "Creative portfolio"
theme = "creative"
#languageCode = "de-DE"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  #style = "default"
  #description = "Describe your website"
  #copyright = "&copy;2016 Your name or company"
  #sidebarAbout = [
  #  "I am a creative illustrator and graphic designer with more than 10 years of experience.",
  #  "Originally from Toronto, currently based in London."
  #]

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
  facebook      = "full page or profile url in facebook"
  googleplus    = "full profile url in googleplus"
  email         = "email@example.com"
  twitter       = "full profile url in twitter"
  linkedin      = "full profile url in linkedin"
  stackoverflow = "full profile url in stackoverflow"
  instagram     = "full profile url in instagram"
  github        = "full profile url in github"
  gitlab        = "full profile url in gitlab"
  youtube       = "full profile url in youtube"
  whatsapp      = "wa.me service link"

